version: 1.0.{build} 
image: Visual Studio 2017 
build_script: 
  - cmd: dotnet pack -c RELEASE
test: off
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
artifacts:
  - path: '**\*.nupkg'
    name: Nuget
nuget:
  
  disable_publish_on_pr: true